---
:project:
  :which_ceedling: gem
  :ceedling_version: 1.0.1
  :use_mocks: TRUE
  # ¡IMPORTANTE!: preprocesadores activos para detectar includes "mock_*.h"
  :use_test_preprocessor: :all
  :use_deep_preprocessor: :all
  :use_backtrace: :simple
  :use_decorators: :auto
  :build_root: build
  :test_file_prefix: test_
  :default_tasks:
    - test:all
  :test_threads: 8
  :compile_threads: 8

:plugins:
  :enabled:
    - module_generator
    - gcov
    - report_tests_log_factory
    - report_tests_pretty_stdout

# Para que CMock sea “verboso” y detecte mejor los includes
:cmock:
  :verbosity: 3
  :mock_prefix: 'mock_'
  :when_no_prototypes: :warn
  :enforce_strict_ordering: true

:report_tests_log_factory:
  :report_path: build/artifacts/test
  :reports:
    - json
    - junit
    - cppunit
    - html

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - inc         # ← carpetas (sin /**)
    - ports       # ← carpetas (sin /**)
  :support:
    - test/support
  :libraries: []

:defines:
  :test:
    - TEST

:gcov:
  :summaries: TRUE
  :report_task: FALSE
  :utilities:
    - gcovr
  :reports:
    - HtmlBasic
    - Cobertura
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90
    :xml: true
    :xml_filename: build/artifacts/gcov/gcovr/GcovCoverageCobertura.xml

# Evita problemas de PATH con gcovr en Windows
:tools:
  :gcovr:
    :executable: python
    :name: gcovr
    :arguments:
      - -m
      - gcovr
